language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: ZQSqiimI6FM5cKPfCGY6MNNwogfvKyn5ibHkQpSPRwNCov4aZJQpkZFRMpEeqWMJ5tgxvjDsQFH+5T6qMoQA0ffUSFHvh6sSCbaVn3hDWX2xe9KubSSk3ZE54R8hgjmL4ndIp+6foMP50y5Pn56O9fyv65oZra4hLNkVROqHcJGZAktHHcuV38lMrRQtgwJrZQUdAC+DuwKL/SpVaCjC9P4KW9oY53VdokB9BKjWb9UiNsq51MXWi8jCZGCCMthzIbWmox+f+31ZoV9wv+if89o5tYKOQlEuA0+3mF4oVSZqMYHNofC08WksmpIDoYjIN6x3sjGiV2RB8DArkAwe7El0CYWbT68rElznWBJc8aPMyUMLYpjZueCxnRie01A7o8iNaPnS5m+2KysCjVgHLoqWbeN8Jc94UYy6fSXq7443jZXYnFJJHDD87qIlyQy5UUJRe3jfcgDixZyJthGqrdNBURIPaaNyYZtt87pBmAX/hdb1zYGcibNuTMLo20rrkSaoc/n4RTbbex74xbH6berl4U/Mqp5gtXbdT87r9jlixrKSUHdyY0PosvdiExZLoWDcom9sRcqB5u/g+y10f5C8zI5zOH5LSwFwhA7roHEMBctSAbEJq9F9PPHXGNbyZ/HMp+oVpoE1hhCiqUna0tISIjR253T4o+hNa4JT8tg=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
